### PR TITLE
Feature/patrick brown1/994471899 admin page table design

### PR DESCRIPTION
**Pull request by PatrickBrown1**
### Administrative Info
Monday Board ID: 904869142
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Monday Item ID]-[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
- Created item table for admin page
- Can filter based on four categories (Main Dish, Appetizer, Side, Drink)
- Can search
- Reflects database items (Based on Thomas' new schemas)
- Items are removable

### Testing
How did you confirm your changes worked? 
- Added items to database through postman and checked for update on webpage
- removed from webpage

### Confirmation of Change 
It only let me upload a 480p video, sorry if it's low quality

https://user-images.githubusercontent.com/29768212/106222238-f5fcbc00-6193-11eb-8ee4-04973c1d4675.mov

### CODE REVIEW

**Review by aaron-kirk — APPROVED** [review]
Looks pretty clean. No complaints.

**Comment by PatrickBrown1** [comment]
image
Here's a screenshot from after my most recent changes

**Review by Amrit-S — CHANGES_REQUESTED** [review]
Looks really good Patrick! A few things:

1. Make the Delete Pop-Up centered on the screen, and have the color of the "Remove Item" to be gold instead of blue.

2. Make the category drop down a bit wider, and have its height match the height of the search bar. Right now its height is a bit bigger than the search bar. Also, make the distance between it and the search bar a bit larger. 

3. Actual Bug: So right now, if the price string for a size is an empty string, you are still rendering the size, when you shouldn't display that size at all. Heres an example of what I mean:

Screen Shot 2021-02-05 at 1 54 36 PM
Screen Shot 2021-02-05 at 1 54 43 PM

**Review by Amrit-S — APPROVED** [review]
LGTM

**Pull request merged**
