### PR TITLE
Refactored Navbar

### PR DESCRIPTION
**Pull request by aaron-kirk**
Added mobile functionality
(collapsing + hamburger menu)

### Administrative Info
Monday Board ID: 904869142
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Monday Item ID]-[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
- Changed color of navbar to align with the palate on Figma
- Added Admin, Logout, and Login options to the navbar depending on whether user is logged in
- Navbar collapses on mobile view width; pages replaced with hamburger icon
- Pages accessible in collapsing menu on mobile

### Testing
How did you confirm your changes worked? 
- Made isAuthorized() return true to ensure Admin and Logout options show up as intended
- Likewise with returning false and the Login option
- Changing window size causes page list to appear/disappear and be replaced with a hamburger icon
- Toggling the menu on mobile and changing back to desktop size still shows the page list as expected

### Confirmation of Change 
[Result](https://gyazo.com/594c0071d3e9ea61c6786dce99dc838d.gif)

### CODE REVIEW

**Review by Amrit-S — CHANGES_REQUESTED** [review]
Good job on getting the navbar to collapse! A few things though:

1. For Desktop, your spacing is way too much between the different pages. They need to be closer together. Also, your UWEAST Logo is floating near the top of the page when it should be in-line with the rest of the lettering. 
Screen Shot 2021-01-17 at 11 41 57 PM

2. For Mobile, the hamburger dropdown takes up the entirety of the page, and it shouldn't do that. It should take up perhaps a 1/3 - 1/2 of the page. Also, the font size for the pages listed is way too large so reduce it a bit.

**Review by navidboloorian — CHANGES_REQUESTED** [review]
Code doesn't look bad. Only issue I see is that the spacing between terms on the navbar is sort of wide and logo isn't vertically aligned.

**Comment by aaron-kirk** [comment]
Used bootstrap styling instead of my own; spacing is decreased and logo is vertically aligned.

[GIF of changes](https://i.gyazo.com/580a5a618a2a57a59736eba086ca8877.gif)

**Review by Amrit-S — CHANGES_REQUESTED** [review]
Looks much better Aaron! Just asking for a few stylistic changes so it matches more closely with the design NavBar we were given:

1. Can you have the size/color opacity of the pages mock the [design navbar](https://xd.adobe.com/view/ea4f1f5c-de68-43d8-44d7-ae714b1271d6-9c7e/)? They should look slightly bigger and more white essentially. We don't have the logo as of yet so just ignore that part.

2. Also, can you add a hovering effect on the pages where the color transitions to some sort of complementary gold/yellow? Upon clicking on that page, the text color should stay gold/yellow until another page is clicked. Take a look at the navbar of this [site](https://dynamicsperformanceteam.com/#/) to get an idea of what I'm talking about. This is a common feature in general so I would guess this to be something built-in that you can use.

**Review by navidboloorian — APPROVED** [review]
Looks good to me

**Comment by aaron-kirk** [comment]
Adjust size of navbar and color of links; added hover and active page coloration.

[See result](https://gyazo.com/ebe5451da94277d1d91e178ce189a064.gif)

**Review by Amrit-S — APPROVED** [review]
Looks great!

**Pull request merged**
