### PR TITLE
update order schema / spelling

### PR DESCRIPTION
**Pull request by thomas-gg**
### Administrative Info
Monday Board ID: 904869142
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Monday Item ID]-[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
- updated the orders schema and fixed accommodations

### Testing
How did you confirm your changes worked? 
- inserting to orders with and without the subattributes of the Order (i.e. Accommodations and specialInstructions)

### Confirmation of Change 
```json 
{
        "Customer": {
            "Name": "yes",
            "Email": "yes@email.com",
            "Phone": "123-456-7890"
        },
        "Pickup": "2020-10-20T23:20:00Z",
        "Timestamps": true,
        "isCompleted": true,
        "PayPal": {
            "Amount": "0.04",
            "transactionID": "1234567890"
        },
        "Order": [
            { "item": "chicken", 
            "quantity": 12, 
            "Accommodations": "gluten-free",
            "specialInstructions": "special instruction"
        }]
}
```

### CODE REVIEW

**Review by aaron-kirk — APPROVED** [review]
Pro spelling, I approve

**Review by Amrit-S — CHANGES_REQUESTED** [review]
So for Order Array, you are missing the size attribute. And also, make the item, quantity, and size attributes required.

**Review by Amrit-S — CHANGES_REQUESTED** [review]
Make accomodations in order array lowercase so it fits in with the rest of the structure

**Review by Amrit-S — APPROVED** [review]
LGTM

**Pull request merged**
