### PR TITLE
Cart Icon Items Badge

### PR DESCRIPTION
**Pull request by alexrodpas**
### Administrative Info
Monday Board ID: 904869142
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Monday Item ID]-[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
- Added a badge to the cart icon for both tablet and mobile to reflect how many items are currently in the cart

### Testing
How did you confirm your changes worked? 
- Added items to the cart, checked that the badge's number was correct. Did the same with removing items.
- Tried different sizes to make sure the NavBar still looked good.
  - There is a bug where the NavBar doesn't render the mobile cart and hamburger menu exactly at 1199px width.

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

| View on desktop |
| --- |
| image |

| View on tablet |
| --- |
| image |

| View on mobile |
| --- |
| image |

### CODE REVIEW

**Review by Amrit-S — CHANGES_REQUESTED** [review]
Great job guys! Really looks good! 

Just had one issue with the size of the cart icon once you're near tablet/desktop mode. 
Before


Then collapsing it back a few pixels more:
After


First image's cart is too big for that stretch of time, it should be more like the second image's cart.

**Review by dnanjunda — APPROVED** [review]
LGTM!

**Review by Amrit-S — CHANGES_REQUESTED** [review]
Message over Slack - but I would suggest making the NavBar be evenly spaced with the logo, cart and hamburger text once the width size <= 375 px.

**Review by Amrit-S — APPROVED** [review]
LGTM

**Pull request merged**
