### PR TITLE
updated the orders dropdown row

### PR DESCRIPTION
**Pull request by amiteshksharma**
### Administrative Info
Monday Board ID: 904869142
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Monday Item ID]-[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
- Edited the orders page dropdown to include more information

### Testing
How did you confirm your changes worked? 
- Just looked at the page, changed the width to make sure it stayed consistent

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

| Orders |
| --- |
| image |

### CODE REVIEW

**Review by Amrit-S — CHANGES_REQUESTED** [review]
Change the ordering (left to right) of the expanded row to this: "Item", "Qty", "Size", "Accommodations", and "Special Instructions". 

Also, add in file headers to changed files indicating the purpose of the file + any relevant things a developer would need to know when looking at the file.

**Review by PatrickBrown1 — CHANGES_REQUESTED** [review]
Looks good for the most part! My only concern is the styling on lines 26, 27 of Orders.css. Having such a long explicit chain is a bit weird. I would try to just make a new class and put it in the HTML for the table header column. I know changing css for third party components is a bit weird, but I've had luck overriding background colors with !important and classes.

**Review by Amrit-S — CHANGES_REQUESTED** [review]
Alright, Amitesh it looks better. However, you need to wrap your columns for the expansion so if the text for a particular column (most likely accommodations) is very long, your table doesn't start looking weird:
Screen Shot 2021-02-16 at 1 34 11 AM



Look into this, but essentially after a certain width, the text should wrap around to the next row, and continue downwards instead of to the right like it does in the above image. Do this for all the columns, but especially for the "Accommodations" and "Special Instructions" columns.

**Review by PatrickBrown1 — CHANGES_REQUESTED** [review]
I would also change the sizing of each element in the drop-down. In my eyes, special instructions and accommodations should be much larger than size, quantity, and items because size can only take two strings "individual" and "family", whereas accommodations and special instructions can be (potentially infinitely) long strings. If you make these containers bigger, you won't have to wrap as much content and you wouldn't encounter overflow very often. ( I know it goes a little against the designs, might want to check with @Amrit-S on this)

**Review by Amrit-S — APPROVED** [review]
LGTM.

Discussed over Slack: Expanded containers for Accommodations & Special Instructions, with adjusted spacing for all.

**Review by PatrickBrown1 — APPROVED** [review]
Looks good! Nice work

**Pull request merged**
