### PR TITLE
Feature/patrick brown1/1061986824 desktop admin menu responsive

### PR DESCRIPTION
**Pull request by PatrickBrown1**
### Administrative Info
Monday Board ID: 904869142
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Monday Item ID]-[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
- Fixed responsiveness of Admin Menu Page and its modals
- Added featured filter to the admin menu list
- Commented on AdminMenuPage.js PayPal.js AddMenuItemModal.js EditMenuItemModal.js

### Testing
How did you confirm your changes worked? 
- Changed sizes on the screen to make sure it responded well
- Toggled featured and checked feature filter

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.
image
image
image

### CODE REVIEW

**Review by amiteshksharma — CHANGES_REQUESTED** [review]
Hey Patrick, this looks great but I got a couple of comments/notes about some of the aspects. 

1) The Columns doing some weird thing where the column header does not move with the column itself. When scrolling sideways on smaller screen size, for example, 701px width, it has this weird effect. This also occurs with the "feature" and "item name" column header. 

image

2) Change the alert to something like Amrit has for notifying the user on the login/signup/reset password. It looks cleaner and I think it will keep the website consistent. I used a snack box for this, which is in the Material UI if I'm not mistaken. I noticed this alert occurs when a user successfully adds an item or if there is some error with adding the database. Use a snackbox for both. 

image

image

3) Searchbar. Is there to make it live so results occur for every character inputed? If so, is this a feature we want to implement? This is just a question I think this is fine either way. One comment I could have is to add a button having the "search" icon in case the user gets confused, but I would take these comments up with @Amrit-S.

**Comment by PatrickBrown1** [comment]
> 1. The Columns doing some weird thing where the column header does not move with the column itself. When scrolling sideways on smaller screen size, for example, 701px width, it has this weird effect. This also occurs with the "feature" and "item name" column header.

This is a result of the sticky header for the MUI table, on horizontal scroll it will try to keep the header for that cell in vision for as long as possible before overriding it with the next header. Checked in with @Amrit-S and the design team decided to get rid of the sticky header, so this should be fixed.

> 2. Change the alert to something like Amrit has for notifying the user on the login/signup/reset password. It looks cleaner and I think it will keep the website consistent. I used a snack box for this, which is in the Material UI if I'm not mistaken. I noticed this alert occurs when a user successfully adds an item or if there is some error with adding the database. Use a snackbox for both.

Updated! Good call

> 3. Searchbar. Is there to make it live so results occur for every character inputed? If so, is this a feature we want to implement? This is just a question I think this is fine either way.

Made the search bar update on keystroke instead of when you hit enter.

**Review by Amrit-S — CHANGES_REQUESTED** [review]
Looks really good Patrick, and compliments on the thorough comments. Few things however: 

1. Change the admin panel from "Menu Items" to "Edit Menu"

2. Wrap the excess part of the admin panel around to a new line, so there's isn't overflow. Horizontal scroll is fine for table components, but not for other parts of the page. I think you'd just have to move "Reset Password" to a new line, and maybe center the admin panel a little bit. 
Screen Shot 2021-02-22 at 3 07 03 PM

3. For the featured filter on the dropdown, have it come after "All" and before "Appetizers" to keep it consistent with the Menu page. 

4. For your add/edit modules, can you have the the margins for the "Description" and "Price" be the same as the "Size" and "Price" value. Right now, the indentation is inconsistent so just **left-align** everything to the headers:
Screen Shot 2021-02-22 at 4 36 03 PM

5. Add some sort of validator on the url that is passed to you. Backend checks if its a URL, but you need to check on your side if the URL is a **valid image url** (i.e., ends in .jpeg, .png, .jpg, etc). You can use [regular expressions](https://stackoverflow.com/questions/9714525/javascript-image-url-verify) to do that, something like this (do not include the .gif as a valid type): 
Screen Shot 2021-02-22 at 4 18 34 PM

If the ^ function returns true, its a valid image url. **If it returns false, it is not a valid image url and you should display some sort of error to the user to indicate this.**

**Review by Amrit-S — CHANGES_REQUESTED** [review]
Looks super duper good Patrick! Really two small aesthetic things, and you should be good to go:

1. Can you add a hover effect to the "x" on accommodations? It should just have its color change from black to red.

2. Also, for the image link validation, can you make the error message at the bottom be specific? Something along the lines of "Image link must have a valid image extension (.jpeg, .jpg, or .png)"

**Review by Amrit-S — APPROVED** [review]
LGTM. Note for next PR, make sure you add comments to all files you touched in the codebase. I believe AdminItemFunctionality.js and Admin.js are untouched for comments.

**Review by amiteshksharma — CHANGES_REQUESTED** [review]
Couple CSS things) 

1) This is how the add menu item looks on my screen 

image

2) The filter dropdown and search bar look a little small as well, but if this is a design choice from Amrit and the design team then its alright with me. 

image


Fix these and then it should be good to go for me.

**Review by Amrit-S — CHANGES_REQUESTED** [review]
Waiting on approval from other reviewer first.

**Review by amiteshksharma — APPROVED** [review]
LGTM!

**Review by amiteshksharma — APPROVED** [review]
LGTM. make sure to pull from main if you haven't done so

**Review by Amrit-S — APPROVED** [review]
LGTM Patrick! Great job!!

**Pull request merged**
