### PR TITLE
Feature/thomas gg/1054018720 menu images collection schema routes

### PR DESCRIPTION
**Pull request by thomas-gg**
### Administrative Info
Monday Board ID: 904869142

### Changes
What changes did you make?
- Added schema/services/routes for menuItem
- routes are '/' (GET) and '/changeMenuImage' (POST)

### Testing
How did you confirm your changes worked? 
- Get request with nothing in DB --> imageUrl: null
- Can't add empty string
- Adds any string and adds any other string

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.
For '/changeMenuImage' (POST) the body is
```json
{
    "imageUrl": "https://i0.wp.com/www.alltherooms.com/blog/wp-content/uploads/2019/02/Feature-10-Best-Taco-Shops-in-San-Diego-By-Joshua-Resnick-Shutterstock.jpg?fit=1000%2C667&ssl=1"
}
```

### CODE REVIEW

**Review by Amrit-S — CHANGES_REQUESTED** [review]
So Thomas it looks good and all, but I'm very curious as to why you submitted the PR for a Collection called _MenuImages_ and your entire implementation refers to it as _MenuItems_?

**Review by Amrit-S — CHANGES_REQUESTED** [review]
1. Add a file header including the purpose of the file + any necessary details. Add function headers for all your routes. Make use of the @description and @return params when making your headers. Make sure to specify clearly what you will return, for each route (general + edge cases).

2. For your /changeMenuImage route, have the url be validated as a valid URL by using the built in` .isURL()` function.

**Review by Amrit-S — APPROVED** [review]
LGTM

**Review by dnanjunda — APPROVED** [review]
LGTM. Just merge main into your branch.

**Pull request merged**
