### PR TITLE
Feature/thomas gg/959122857 emails add delete access

### PR DESCRIPTION
**Pull request by thomas-gg**
### Administrative Info
Monday Board ID: 904869142

### Changes
What changes did you make?
- added schema for email
- added for route email /insert /get /remove
- added services for email to communicate with mongo.

### Testing
How did you confirm your changes worked? 

For /insert
- invalid email (conforming to express-validator)
- no email

For /remove
- invalid email (conforming to express-validator)
- no email
- incorrect email
- delete twice in a row

For /get
- tested with and without emails in db

### Confirmation of Change 
In order to test make post requests with the required body information.

### CODE REVIEW

**Review by Amrit-S — CHANGES_REQUESTED** [review]
Hey Thomas good work. 

Just make sure to add the required and unique keywords to the Emails Schema. Also, make any query updates as needed to the addEmail functionality after the unique keyword is assumed. 

Also, make sure that any future PRs come off the main branch, so you don't have files from another open PR request and the changed files are solely the ones having to do with the feature in this branch!

**Review by dnanjunda — APPROVED** [review]
Good job! LGTM

**Review by Amrit-S — CHANGES_REQUESTED** [review]
Looks good Thomas! Uncomment the findAllEmails() function in services and allow it to be exported. Dhanush will need to use it when figuring out who to send emails to on UWEAST's side.

**Review by Amrit-S — APPROVED** [review]
LGTM

**Pull request merged**
