### PR TITLE
Feature/aaron kirk/994472692 menu pop up desktop

### PR DESCRIPTION
**Pull request by aaron-kirk**
### Administrative Info
Monday Board ID: 904869142
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Monday Item ID]-[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
- Generally adjusted styling to align with updated design.
- Added mobile formatting to align with updated design.
- Refactored inputs to use new schema structure.
- Dynamic food size and accommodation options.
- Cut off floating point imprecision in prices (prices are now always 2 decimal places instead of something like $42.0800000001).

### Testing
How did you confirm your changes worked?
- Hard-coded a faux item based on new item schema and passed it to the my pop up.
- Varied the number of available size and accommodation options in hardcoded item.
- Checked for visual issues for different screen sizes.

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

High Quality Content:
https://youtu.be/4l6YVfzvvtg

### CODE REVIEW

**Review by Amrit-S — CHANGES_REQUESTED** [review]
It looks **sooo** good! Great great work Aaron!!

Just a few things that need to be tweaked though:

1. You still have floating point numbers (suggest using Number's toFixed() function): 

Screen Shot 2021-02-07 at 7 50 34 PM

2. Add the $ sign as well for the sizes portion (see the same image above with family). It should be  +($6.69) not +(6.6999999999).

**Review by navidboloorian — APPROVED** [review]
LGTM!!

**Review by Amrit-S — CHANGES_REQUESTED** [review]
Much better! Requesting another change on Accommodations to make it user-friendly. 

1. If no accommodations exist, do not render the Accomodations group. It should go straight from Size --> Special Instructions 

2. Add a character limit of 75 on the Special Instructions text. 

Sorry about this! I'm going against the design decision since in terms of UX that part is a bit confusing

**Review by Amrit-S — APPROVED** [review]
Amazing!

**Pull request merged**
