### PR TITLE
Linting setup

### PR DESCRIPTION
**Pull request by justinyaodu**
### Changes
What changes did you make?
- Set up ESLint and Prettier
- Add NPM scripts for linting and formatting code
- Add a Git pre-commit hook to check for lint errors
- Autofix some lint errors and reformat code

### Testing
How did you confirm your changes worked? 
- Cloned the repository, checked out this branch, ran `npm install` on the frontend and backend, and verified that the Git pre-commit hook prevents committing when there are lint errors
- CircleCI config will be tested after merging

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

- See the Testing section

### CODE REVIEW

**Comment by justinyaodu** [comment]
Navid and I discovered that the frontend no longer compiles on this branch, so I'm going to close this PR until I've tested it more thoroughly. My apologies!

**Comment by justinyaodu** [comment]
Figured it out. The stricter ESLint config was producing errors that weren't there before (which is what we want), except Create React App aborts the build if there are ESLint errors. I fixed this by setting an environment variable which converts ESLint errors to warnings as far as Create React App is concerned.

**Review by navidboloorian — APPROVED** [review]
LGTM!

**Review by Amrit-S — APPROVED** [review]
LGTM. Note: Lots of unresolved lint errors restated as warnings for frontend

**Pull request merged**
