### PR TITLE
Fixed mobile and tablet displays

### PR DESCRIPTION
**Pull request by navidboloorian**
### Administrative Info
Monday Board ID: 904869142
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Monday Item ID]-[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
- Made height of contact form inherit instead of fixed
- Made tablet pages stack instead of showing up side by side

### Testing
How did you confirm your changes worked? 
- Testing on all dimensions in dev tools

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

**iPad display**
image

**Phone display**
image

### CODE REVIEW

**Review by Amrit-S — CHANGES_REQUESTED** [review]
Looks good for the most part Navid. 

1. My largest concern is the tablet width size region for your display. Its mostly fine for vertical, but for desktop and tablet horizontal it explodes on the screen. Case in point:
Screen Shot 2021-02-22 at 11 13 03 PM
Screen Shot 2021-02-22 at 11 13 17 PM
^ Desktop contracted to that size

The iPad one I could somewhat take, but that desktop one definitely needs fixing

They're around the same width I'm guessing so if you fix it for one, it should fix for both


2. Make to add comments to your files. I didn't see any for pages/Contact.js

**Review by Amrit-S — APPROVED** [review]
LGTM Navid - great job!

**Review by Amrit-S — COMMENTED** [review]
LGTM but waiting on approval from other reviewer first.

**Review by Amrit-S — CHANGES_REQUESTED** [review]
LGTM but waiting on approval from other reviewer first.

**Review by alexrodpas — APPROVED** [review]
I haven't run into any issues. Good job! Remember to update from main before merging.

**Review by Amrit-S — APPROVED** [review]
LGTM! Great work!

**Pull request merged**
