### PR TITLE
create signup and register routes

### PR DESCRIPTION
**Pull request by thomas-gg**
### Administrative Info
Monday Board ID: 904869142

### Changes
What changes did you make?
- added to user/register and user/login --> responds to invalid requests and both return the email of the user as well as the jsonwebtoken.
- added validation middleware relating to express-validator
- deleted the node_modules from the repo and modified the .gitignore

### Testing
For login (post request to user/login) requests tested:
- password less than 6 characters
- no password / incorrect password
- no email
- invalid email (conforming to express-validator)
- login with no users in db

For register (post request to user/register) requests tested:
- password less than 6 characters
- no password
- no email
- no secret
- invalid email (conforming to express-validator)
- duplicate user

### Confirmation of Change 
In order to test make post requests with the required body information.

### CODE REVIEW

**Review by Amrit-S — CHANGES_REQUESTED** [review]
Hey Thomas - it looks good for the most part. Just a few things. 

1. For Users Schema, make the email and password to be required. 

2. Inside of services/users.js, have your addNewUser() function only responsible for adding a new user if it isn't a duplicate. Have any checks for whether the register_secret matches the secret given in the request be done inside the 'register' route itself.

 3. Also, when creating tokens in both of your routes, you had your secret be register_secret when it should be jwt_secret.

**Review by Amrit-S — APPROVED** [review]
Looks good!

**Review by dnanjunda — CHANGES_REQUESTED** [review]
Hey Thomas, just a minor fix. In routes/user.js, you misspelled register_secret as regiter_secret. Other than that, it looks good to me!

**Review by dnanjunda — APPROVED** [review]
lgtm

**Pull request merged**
