### PR TITLE
feature/PatrickBrown1/948885943-paypal-smartbuttons-on-create

### PR DESCRIPTION
**Pull request by PatrickBrown1**
### Administrative Info
Monday Board ID: 904869142

### Changes
What changes did you make?
- Implemented the PayPal Buttons onCreate method in PayPal.js. This is based on the cart props. I assumed it took a particular form. Can be easily changed if the actual cart object is different
- Upon order completion, both the merchant and customer get receipts from paypal
- Note: The individual item prices and total prices must add up precisely or else PayPal responded with 400
 
### Testing
How did you confirm your changes worked? 
- PayPal Sandbox testing showed that the merchant received and the customer spent the amount of money specified by the cart
- PayPal Sandbox testing showed that both the merchant and the customer received confirmation emails
- The API response always returns the customer's information (phone number, email, name), tested with Paypal account, and credit card

### Confirmation of Change 
Confirmation to Merchant
Screen Shot 2021-01-08 at 5 02 00 PM
Confirmation to Customer
Screen Shot 2021-01-08 at 4 22 34 PM
Recording of Checkout Process (The account was already logged in, but it would prompt a log in before the payment selection screen)
https://user-images.githubusercontent.com/29768212/104079706-6fc70880-51d9-11eb-8752-156503955d4b.mov

### CODE REVIEW

**Review by Amrit-S — APPROVED** [review]
Looks good Patrick!

**Review by amiteshksharma — CHANGES_REQUESTED** [review]
Inside "frontend/public/index.html", the PayPal script has a client-id that anyone can see in this repo. Does this matter or do we want to keep this client-id hidden? Besides that, LGTM.

**Comment by PatrickBrown1** [comment]
> Inside "frontend/public/index.html", the PayPal script has a client-id that anyone can see in this repo. Does this matter or do we want to keep this client-id hidden?

The best way to hide it would be to make the PayPal API calls through the backend, but that's not super feasible with the deadline we have in place (would be more work for backend). I asked @Amrit-S about this and we decided to leave it there for now and change it later if we have time.

**Comment by amiteshksharma** [comment]
> > Inside "frontend/public/index.html", the PayPal script has a client-id that anyone can see in this repo. Does this matter or do we want to keep this client-id hidden?
> 
> The best way to hide it would be to make the PayPal API calls through the backend, but that's not super feasible with the deadline we have in place (would be more work for backend). I asked @Amrit-S about this and we decided to leave it there for now and change it later if we have time.

Alright. I'll update my review then. Good work

**Review by amiteshksharma — APPROVED** [review]
LGTM

**Pull request merged**
