### PR TITLE
Feature/amiteshksharma/1024868713 navbar styling

### PR DESCRIPTION
**Pull request by amiteshksharma**
### Administrative Info
Monday Board ID: 904869142
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Monday Item ID]-[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
- Added the UWEAST Logo on the navbar
- Added the cart icon when the viewport is on mobile
- hide the admin/orders/login tab when on mobile

### Testing
How did you confirm your changes worked? 
- I changed the viewports and checked to see if they changed accordingly

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

| Home page Navbar |
| --- |
| Home_Page_Logo |

Menu_page_Cart

Navbar_dropdown

### CODE REVIEW

**Review by navidboloorian — COMMENTED** [review]
Looks good generally speaking. Only issues I see is that the banner overlaps the navbar on desktop and the cart icon shows up on tablet as well which I'm not sure if it needs to. Otherwise great stuff.

**Review by Amrit-S — CHANGES_REQUESTED** [review]
The desktop version seems fine, but the mobile version is really buggy and is just not working at all for me. 

The mobile version does not have all the icons properly aligned - they seem to be drifting down the page and into the banner. Second, the hamburger icon for mobile is not clickable. Clicking on it should display all the pages, but clicking on it right now is doing absolutely nothing. 

Screen Shot 2021-02-07 at 7 10 16 PM

**Review by Amrit-S — APPROVED** [review]
LGTM!

**Review by thomas-gg — APPROVED** [review]
Super clean design and I really like how the mobile scroll works, sometimes the wording of the uweast icon doesn't scale very well if you zoom in or out (i.e. the word uweast is below the all orders require 20 dollar minimum bar, but everything is very well done and seems to work in mobile as well.

**Pull request merged**
