### PR TITLE
Feature/navidboloorian/994472823 menu page general design

### PR DESCRIPTION
**Pull request by navidboloorian**
### Administrative Info
Monday Board ID: 904869142
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Monday Item ID]-[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
Added banner, added mobile/tablet display, changed price location to prevent overlap with text

### Testing
How did you confirm your changes worked? 
Checked with multiple different screen dimensions added lots of items to see how overlap worked and how they resized.

### Confirmation of Change 
banner
image
mobile 
image
tablet
image
reworked item
image

### CODE REVIEW

**Comment by aaron-kirk** [comment]
The mobile version looks nice. Tablet version is also good. I like the new item listings. 

I noticed that the Navbar isn't positioned fixed (I think) on desktop (for me ? ), but the banner is, so if you scroll the navbar goes away but it looks like the banner is floating there in empty space. I think you could either have it scroll with the navbar (maybe consider having it position: sticky to top: 0, if that's something you think would be nice) or make navbar also fixed (not sure if that's your problem though; might be something I messed up on when I did it previously tbh...).

Lastly, the banner is kind of hard to look at. I would recommend adding some padding in the y just to give it some space and also playing with the colors—yellow on white doesn't have much contrast. It is kind of difficult considering the palate is like brown, yellow, and white, but I think black text on a yellow blacking might be better.

That said, you're a pro, Navid :DD everything still looks nice and fun

**Review by aaron-kirk — CHANGES_REQUESTED** [review]
The mobile version looks nice. Tablet version is also good. I like the new item listings.

I noticed that the Navbar isn't positioned fixed (I think) on desktop (for me ? ), but the banner is, so if you scroll the navbar goes away but it looks like the banner is floating there in empty space. I think you could either have it scroll with the navbar (maybe consider having it position: sticky to top: 0, if that's something you think would be nice) or make navbar also fixed (not sure if that's your problem though; might be something I messed up on when I did it previously tbh...).

Lastly, the banner is kind of hard to look at. I would recommend adding some padding in the y just to give it some space and also playing with the colors—yellow on white doesn't have much contrast. It is kind of difficult considering the palate is like brown, yellow, and white, but I think black text on a yellow blacking might be better.

That said, you're a pro, Navid :DD everything still looks nice and fun

**Review by aaron-kirk — APPROVED** [review]
Banner is properly positioned with the navbar now—nice. And the banner is much more readable now.

**Review by Amrit-S — APPROVED** [review]
Impeccably done! Menu is absolutely gorgeous - great job!!!

**Pull request merged**
