### PR TITLE
Implement automated emails

### PR DESCRIPTION
**Pull request by dnanjunda**
### Administrative Info
Monday Board ID: 904869142
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Monday Item ID]-[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
- added email templates for customer and uweast copies
- implemented autoEmails/automate route

### Testing
How did you confirm your changes worked? 
- invalid input without Customer, Pickup, PayPal, or Order fields in request body
- call route with no emails in database

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

To test autoEmails/automate, make a post request with the following body:

Screen Shot 2021-01-18 at 12 43 17 PM

### CODE REVIEW

**Review by Amrit-S — CHANGES_REQUESTED** [review]
Looks good Dhanush. Please **remove your .env file** however, and instead move that confidential information regarding email and password to the Project Docs under email automation.

Also, just one actual edit. The PickUp is of type Date in the request, so it includes both date and time. When you write to the **_emails_** (not the Orders DB!), make sure to separate the two or else it just looks weird to the user:
Screen Shot 2021-01-21 at 10 45 04 PM

And my request body for that...
Screen Shot 2021-01-21 at 10 45 25 PM

**Review by thomas-gg — APPROVED** [review]
LGTM

**Review by Amrit-S — CHANGES_REQUESTED** [review]
A few additional detail requests:

1. Replace the "," into "at" and take out the seconds in the time (it's just weird to have it that specific) so its "1/23/2021 at 11:26 AM" .

2. I think right now you have Miriam's email be hardcoded onto there. Instead, have it replaced to be whatever email you got back when you queried the emails DB.

3. At the very bottom of the email, I would also briefly state that this is an automatic email. "NOTE: This is an automatically generated email, please do not reply."

**Review by Amrit-S — APPROVED** [review]
Looks good!

**Pull request merged**
