### PR TITLE
Edit item functionality for mobile and other bug fixes for cart

### PR DESCRIPTION
**Pull request by dnanjunda**
### Administrative Info
Monday Board ID: 904869142
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Monday Item ID]-[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
- Implemented edit item functionality for mobile cart
- Increased font size for mobile cart
- Fixed bug where cart didn't change to popup when window size changed from mobile to desktop
- Changed numbering of cart items in cart summary
- Changed color of return buttons
- Added comments to all files that I touched

### Testing
How did you confirm your changes worked? 
- Tried editing items on cart page in mobile
- Opened cart on mobile and increased window size to desktop

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

Mobile cart:
https://user-images.githubusercontent.com/57281768/109474345-454f3a00-7a29-11eb-88ea-07abae2d8cd8.mov

Cart Summary:
Cart

### CODE REVIEW

**Review by Amrit-S — CHANGES_REQUESTED** [review]
Alright, Dhanush, the cart looks really nice and in general is working fine so good job on that, but I caught quite a few bugs. The videos are pretty self-explanatory so I won't give too much textual background:

1. **Removing Items From Cart**

Some instance of remove causes bug crashes. I've noticed this particularly (though I may be wrong) for items that have the same name in the cart. 
https://user-images.githubusercontent.com/42155577/109583549-eafbbb00-7ab4-11eb-8a7d-07300482be53.mp4

Removing items when there is more than like 4 items in the cart, causes multiple items to be removed. 
https://user-images.githubusercontent.com/42155577/109583564-ef27d880-7ab4-11eb-9a8a-b2622a660b63.mp4

2. **Pixel X Problems with Orientation Changes from Vertical<--> Horizontal** 

Locked Scrollbar on Horizontal view
https://user-images.githubusercontent.com/42155577/109583794-52b20600-7ab5-11eb-9257-3ea91572d53c.mp4

Orientation Change from Horizontal to Vertical causes pop-up cart to be shown, not page cart summary

https://user-images.githubusercontent.com/42155577/109583891-7bd29680-7ab5-11eb-8980-d5acb2657dc8.mp4

3. **Resizing issue when going from Desktop to Mobile screens, causes pop-up menu to be shown for mobile not page menu**

https://user-images.githubusercontent.com/42155577/109583957-973da180-7ab5-11eb-8ca7-106ad4d99e74.mp4

**Review by Amrit-S — CHANGES_REQUESTED** [review]
Lots of the remove functionality was solved, and the transition between NavBar and Desktop is better. Still few things:

1. On Checkout, clicking on the time field crashes the site:

https://user-images.githubusercontent.com/42155577/109648063-fd0a4780-7b0e-11eb-9eec-edf56132e10f.mp4

2. Continued iPhone X problems: There's a really long weird glitch going on and the load time is pretty insane for that phone, when switching from vertical to horizontal:

https://user-images.githubusercontent.com/42155577/109648148-20cd8d80-7b0f-11eb-8dea-52b1e66fe75f.mp4

3. There shouldn't be any prices inside of LocalStorage:
Screen Shot 2021-03-02 at 4 17 33 AM

**Review by aaron-kirk — CHANGES_REQUESTED** [review]
I tried a variety of inputs and tried all the input fields and I couldn't get it to break from that (or replicate the bugs Amrit found, so I guess you fixed them! yay). That said, rendering generally takes quite a while; in fact, I found that changing window size on desktop could take a whole minute to render or (in some cases) just crash the page. Though I couldn't replicate Amrit's iPhone X bug, lag when changing orientation was definitely consistent with her observations. I'm unsure if this is something you can feasible resolve, though. 

photo_2021-03-03_12-17-54

**Comment by thomas-gg** [comment]
LGTM!

**Review by thomas-gg — APPROVED** [review]
LGTM!!

**Review by Amrit-S — APPROVED** [review]
LGTM!! Additional issues and bugs were discussed via Slack. Essentially, cart was optimized by using id tags of each item to make DB calls on item information, so item information would not have to be stored locally. Additionally, cart was optimized further by moving information to cookies exclusively in a more efficient JSON format using key/value arrays instead of fields. Maximum cart limit also enforced, with pop-up occurring once it is reached.

**Review by aaron-kirk — APPROVED** [review]
Not having the same issues with ridiculously long load times; cart full thing seems to be working now. :D

**Pull request merged**
