### PR TITLE
admin emails tab 

### PR DESCRIPTION
**Pull request by amiteshksharma**
### Administrative Info
Monday Board ID: 904869142
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Monday Item ID]-[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
- Amrit fixed the merge conflict error I didn't catch. Accepted incoming changes from the main branch on the Admin.js file. The slight change at line 107 led to the "Emails" tab on the "Admin" page to only render the ChangePrimaryEmail component. A quick fix on this line reverted the changes back to normal. 

### Testing
How did you confirm your changes worked? 
- it should work

### Confirmation of Change 

Screen Shot 2021-02-24 at 1 49 18 AM

### CODE REVIEW

**Review by Amrit-S — APPROVED** [review]
LGTM - issue resolved via slack

**Review by PatrickBrown1 — APPROVED** [review]
Seems good!

**Review by Amrit-S — CHANGES_REQUESTED** [review]
Temporarily taking off approval to fix some merge issues with Github.

**Review by Amrit-S — APPROVED** [review]
LGTM - conflicts resolved via Slack.

**Pull request merged**
