### PR TITLE
Feature/navidboloorian/1047685910 menu page reconfigured layout

### PR DESCRIPTION
**Pull request by navidboloorian**
### Administrative Info
Monday Board ID: 904869142
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Monday Item ID]-[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
- Made cart hidden at 1350px and below
- Made menu item text black and descriptions grey
- Made menu descriptions smaller
- Made filter buttons sticky on scroll
- Fixed overlap bugs

### Testing
How did you confirm your changes worked? 
- Tested on responsive and mobile versions to see how screen adapted

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

Tweaked menu item
| --- |
image

Increased gaps between sections
image

Menu filter has also been changed, upon scroll it will stay at the top rather than moving to the bottom.

### CODE REVIEW

**Review by Amrit-S — CHANGES_REQUESTED** [review]
Looks very nice Navid! Few things:

1. For the max size that you are rendering the 1 item per row layout for mobile, change that to 450px instead of 401px. 

2. Increase your font size for the item descriptions for desktop. Its pretty small. Make sure to increase the line height for descriptions as well (maybe 1.25, or 1.5) 

3. For all mobile version, have the main image on the Menu page be center cropped. Right now, it just seems to be left cropped. 
Screen Shot 2021-02-17 at 2 50 03 AM

4. Once the Cart goes away on Menu Desktop, make sure to expand the menu (if possible) to fill in the empty space on the right. The void looks a bit weird 

Screen Shot 2021-02-17 at 2 55 09 AM

5. Add a file header including the purpose of the file + any necessary details to all .js files you touched

**Review by aaron-kirk — CHANGES_REQUESTED** [review]
Aside from what Amrit mentioned, everything seems fine to me. I definitely second making the description text a bit bigger. It's currently pretty uncomfortable for me to read.

**Review by Amrit-S — APPROVED** [review]
LGTM

**Review by aaron-kirk — APPROVED** [review]
Likewise -- looks good

**Pull request merged**
