### PR TITLE
Feature/patrick brown1/1047123779 admin modals v2

### PR DESCRIPTION
**Pull request by PatrickBrown1**
### Administrative Info
Monday Board ID: 904869142
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Monday Item ID]-[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
- Implemented Add Item Modal
- Implemented Edit Item Modal
- Fixed glitches in categories on Admin Menu Item Chart 

### Testing
How did you confirm your changes worked? 
- Added / Edited many items and looked for changes in the menu page

### Confirmation of Change 

Example Editing an Item
https://user-images.githubusercontent.com/29768212/107829404-a646f480-6d3e-11eb-8cfe-b101f0848948.mov

Example Adding an Item
https://user-images.githubusercontent.com/29768212/107829514-bfe83c00-6d3e-11eb-985f-8d1b44e82154.mov

### CODE REVIEW

**Review by Amrit-S — CHANGES_REQUESTED** [review]
Patrick - _really really_ good job with this! It looks very good and seems to be working pretty well from the different ways I tested it! 

Still, quite a few things though: 

**Aesthetics**
1.  For all accommodations, have the price prefix be "+$" instead of just "$". 
2. For all accommodations, change the "Name" to "Description" 
3. Please add an accommodations header to distinguish the second set of Name/Price pairs from the first. Or at the very least, change the "Add" button to "Add Accommodation". 
4. Change your "Dairy Free" to "Contains Dairy" 
5. For you editing functionality, change the yellow "Add Item" text to "Save". 
6. For all required boxes, please add an asterisk next to their heading so the user knows that they are required. So, Name, Picture Link, Description, Category, and price should all have this. 

**Errors**
This part is my largest concern tbh. Your error validation is on point since it doesn't allow bad requests to go through, but you need to **give some external indication to the user that their request was bad**. A pop-up or snack box appearing indicating that you cannot add/save their changes would be very useful, preferably with useful error messages (i.e., "You have added an accommodation, but with no price", "Description is missing", etc.). Or, you can just highlight the relevant boxes red and skip the error messages - that's fine too. I myself forgot that description was required, and since there was no error pop-up was a bit puzzled for a few minutes since I didn't know if your code crashed, my internet lagged, or if my request was just bad for whatever reason since I didn't get any feedback from the form.

Also, make sure to not ignore this with the accommodations stuff too. 

Also on this, I noticed that you made all required boxes have a red error on them if they weren't filled out, but didn't do this for Description for some reason? Please make it consistent, and have the error box around Description as well. 

**File Structure/Comments** 

1. Add file headers to your changed files with a brief summary of the purpose of the file, and any worth information that a developer would need to know when making sense of the file. 
2. I'm not sure if this is just on my side, but I got a lot of duplicate files when I pulled your PR.

**Review by Amrit-S — CHANGES_REQUESTED** [review]
Patrick, it looks much better :100:. Good job :smile: A few things again, but less than last time:

1. On your asterisk note under size, can you change it to "At least one size must be given a price. If you do not want a particular size available for the item, please leave its price field blank." 

2. Also, for accommodations, is it possible for you to add some sort of delete functionality on those (like an "x" to the right of the row that would allow you to delete that accommodation)?

3. Can you add a bit more spacing between the Description and the buttons on the bottom?

4. Lastly can you add a bit more spacing between these 3 parts at the top? Its a bit cramped right now

Screen Shot 2021-02-16 at 1 08 25 AM

**Review by alexrodpas — APPROVED** [review]
You have done an excellent job (you're making me look bad!). There are only a few minor things that you should consider changing, but aren't essential:

- In the design, the way to close the add/edit item modals is an X icon button at the top right of the modal, instead of the "Close" button at the bottom of it.
- In the design, the edit item modal has a "Save changes" button with no icon.
- When typing in prices with more than 2 decimal places, it seems to round up, except 0.005 stays at 0.00.
- When using the arrows in the price boxes, it increments/decrements prices by $1. I'm not sure if this is intended or the way it is supposed to be, but you should check in with Amrit on that.

Other than that, I have found no bugs or problems with your code. I'm approving your PR since none of these suggested changes are significant. Make sure to update from main before merging.

**Review by Amrit-S — APPROVED** [review]
Fabulous job Patrick!

**Pull request merged**
