### PR TITLE
Admin: edit main menu image modal and functionality

### PR DESCRIPTION
**Pull request by alexrodpas**
### Administrative Info
Monday Board ID: 904869142
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Monday Item ID]-[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
- Changed the Menu page banner to add "All menu items are halal".
- Added a "Change Header" button to the Admin page's "Menu Items" tab.
- When this button is clicked, a new modal renders over the Admin page. It allows the user to change the URL for the header image in the Menu page.
- Filling in the form and submitting it will push the input URL to the database and store it in the MenuImages collection as "ImageUrl".
- Error handling for empty, duplicate, or invalid input.

### Testing
How did you confirm your changes worked? 
- Tried empty, duplicate and invalid input, all of which threw errors as expected.
- Many combinations of opening and closing the modal, reloading the page, adding input, and submitting.
- Checked the URL being stored in the database after a submit to make sure it updated.
- Resizing the window.

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

| Change Header Modal |
| --- |
image

### CODE REVIEW

**Review by navidboloorian — CHANGES_REQUESTED** [review]
It looks good that the db updates although the menu doesn't (guessing this comes later). 
However, there should probably be some image verification. At the moment you can submit any link and it will be put into the db with no problem even if it's not an image.

**Review by Amrit-S — CHANGES_REQUESTED** [review]
Same concern as Navid. Looks good Alex, but you need to have the menu page's header change as well. This will require a slight refactoring of Navid's code, though @navidboloorian might be better in updating that portion since its primarily his code so don't worry about it. 

1. Add some sort of validator on the url that is passed to you. Backend checks if its a URL, but you need to check on your side if the URL is a **valid image url** (i.e., ends in .jpeg, .png, .jpg, etc). You can use [regular expressions](https://stackoverflow.com/questions/9714525/javascript-image-url-verify) to do that, something like this (do not include the .gif as a valid type): 
Screen Shot 2021-02-22 at 4 18 34 PM

If the ^ function returns true, its a valid image url. **If it returns false, it is not a valid image url and you should display some sort of error to the user to indicate this.** 

2. Your modal isn't responsive, and pretty much crashes once you squish it down near mobile. The modal itself should probably be horizontally bigger.  Please fix this:
Screen Shot 2021-02-22 at 4 22 41 PM

3. Other than that, make sure to keep your spacing in the following comment consistent. Your param has an unnecessary amount of white spacing after its param argument: 
Screen Shot 2021-02-22 at 4 13 50 PM

**Review by navidboloorian — CHANGES_REQUESTED** [review]
LGTM generally speaking. I did find some bugs where if you press enter in the form the page reloads. It doesn't seem to actually submit the form successfully but it reloads the page and displays a get query in the url. There is also some button overlap in half width screens (again, since this is admin this may not be a problem). The image checker works only when the extension ends with a .png/.jpeg etc. Image urls sometimes don't end that way but are valid images but this is probably good enough for our purposes unless Amrit doesn't think so. I would also clear the input box because right now it retains the previously entered url and if you press change header again it gives an error.

That's pretty much it. Some of these things may be good enough for our purposes and not be a problem I just wanted to point them out. If Amrit doesn't think these things are an issue I'm good to approve.

**Review by Amrit-S — CHANGES_REQUESTED** [review]
Going back to Navid's comment. If they submit the same url that was pre-given, re-write the error to be "URL is either already being in use or invalid." since backend doesn't allow duplications. 
Screen Shot 2021-02-24 at 7 08 05 PM


Also, for all errors, they should be rendered as a snackbar on the bottom. Alert should only be used if the change was successful.

**Review by navidboloorian — APPROVED** [review]
LGTM

**Review by Amrit-S — APPROVED** [review]
LGTM Alex

**Pull request merged**
