### PR TITLE
Feature/patrick brown1/1033403199 admin page assembly

### PR DESCRIPTION
**Pull request by PatrickBrown1**
### Administrative Info
Monday Board ID: 904869142
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Monday Item ID]-[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
- Implemented nav bar for the admin page that lets you switch between orders, menu items, and email update screens
- Created email update screen where the admin can change the email order confirmations are sent to
- Fixed spacing styling to make sure menu and order tables stayed on viewport height
-
### Testing
How did you confirm your changes worked? 
- Visual rendering
- I'm not sure how to check whether or not the email updated in the database. I got a 200, so it should have worked, but if @thomas-gg could have a look that would be great

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

https://user-images.githubusercontent.com/29768212/107178464-0af20000-6989-11eb-9b3a-8d406c43548a.mov

### CODE REVIEW

**Review by Amrit-S — CHANGES_REQUESTED** [review]
Patrick, major props to you for figuring this out + doing the email stuff while you were at it! A few changes:

1. Biggest change would be that you need to **break up the code**. All the code right now is sitting in one large file and with the amount of different functionalities, its breaking a lot of SRP. **The admin page should now be a selective rendering of other components**. I highly suggest having your admin table/buttons be their own component, and the orders page be its own component @amiteshksharma . Email part is a bit grey line, but if you can make its own component that would be best. 

2. For the "admin navbar", your font size is too big. Make it a bit smaller - follow the design given for reference. 

**Email Page Aesthetic Changes**: 

1. Placeholder text in email should be capitalized from 'email' to "Email". 

2. Change the text on top of the input field to "Order confirmations and customer inquiries will be sent to this email." Also make the text thinner (Light instead of Normal). 

3. There needs to be more spacing of this component from the admin navbar.

**Review by amiteshksharma — CHANGES_REQUESTED** [review]
Took a look and visually, it looks good. Just follow Amrit's advice and follow the design as much as possible. One comment is the header row border on the "Menu Item" tab seems very bold on my screen. 

For the orders page, I had a Orders.js file in the "pages" folder, and some of the components in the OrdersTable.js file can be simplified. For that, I can work on this repo and fix that up before you merge the PR. Just msg me on Slack on what you think about that. I should be able to clean up the code in a day. 

There are also some arrows on the header row for the "Menu items" tab. Don't know if that is on purpose but I think it shouldn't be there. 

Capture

**Comment by PatrickBrown1** [comment]
> 1. Biggest change would be that you need to **break up the code**. All the code right now is sitting in one large file and with the amount of different functionalities, its breaking a lot of SRP. 

Resolved this offline on slack. The components being rendered on the screen are already being imported from their respective files, just some miscommunication.
> 2. For the "admin navbar", your font size is too big. Make it a bit smaller - follow the design given for reference.

Fixed to be more like the design reference
> 1. Placeholder text in email should be capitalized from 'email' to "Email".

Updated
> 2. Change the text on top of the input field to "Order confirmations and customer inquiries will be sent to this email." Also make the text thinner (Light instead of Normal).

I had this in place, it seems like the font we imported didn't have Light font-weight. I imported the 300 font-weight specifically to make this change. It might be a good idea to check out why the original Google font didn't have light.
> 3. There needs to be more spacing of this component from the admin navbar.

Fixed

@amiteshksharma I believe I fixed the issue you found with the scroll bar, but I'm not 100% sure because it wasn't happening on my end. If you could check it out for me that would be great. Also, if everything else is good, you can go ahead and make the changes to OrdersTable.js you were talking about

**Review by Amrit-S — COMMENTED** [review]
Pulled up the recent version - Looks good! Just waiting for @amiteshksharma to update Orders Page, and then will approve the request after a final look

**Review by amiteshksharma — APPROVED** [review]
I organized my files Patrick, so you should be good to go once Amrit approves the changes

**Review by Amrit-S — APPROVED** [review]
LGTM guys!

**Pull request merged**
