### PR TITLE
Feature/amiteshksharma/959775221 order page creation

### PR DESCRIPTION
**Pull request by amiteshksharma**
### Administrative Info
Monday Board ID: 904869142
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Monday Item ID]-[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
- I implemented the orders table
- I added some css styling based on the design team's design
- Note) the styling still needs to be worked on, such as fonts and 
  small design fixed

### Testing
How did you confirm your changes worked? 
- I made the get call and it loaded all the data properly
- No data was missing and no error occurred when clicking on the rows

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

The Orders table design
| --- |
Orders

### CODE REVIEW

**Review by Amrit-S — CHANGES_REQUESTED** [review]
Looks good Amitesh! Few things:

1. Pick Up Details should include both Date and time. Right now its just date. 
2. Your filter right now is entitled Submission Dates but filters on Pick Up. Title it appropriately. 
3. This is going a bit against design, but I honestly think it would be valuable to have a Submission Details column. Can you add that in please - after Amount Paid. It should include both Date and time (referenced by the createdAt attribute)

**Review by Amrit-S — CHANGES_REQUESTED** [review]
Looks good, but all other pages appear to be textually yellow now.

Screen Shot 2021-01-24 at 12 04 52 AM
Screen Shot 2021-01-24 at 12 04 46 AM

**Review by Amrit-S — APPROVED** [review]
LGTM! Great job Amitesh!

**Review by alexrodpas — APPROVED** [review]
It all looks good to me. I ran into no problems, and the code looks clean and organized. I'm not sure if this is exactly like the design, but I'm sure Amrit has already told you whether anything needs to be changed there. Make sure you update from main and resolve conflicts before merging.

**Pull request merged**
